### ISSUE TITLE
Player can't jump

### ISSUE THREAD

**Issue by btzr-io** [RechieKho/ascend#17]
I'm not sure if is just me but I can't get the player to jump. 
It also falls really fast so probably the gravity force is just too strong ?

The issue is gone after using lower values ( between 1 and 2 ) for gravity on  player.gd.

**Comment by RechieKho** [comment]
https://user-images.githubusercontent.com/50512341/217965957-648fa2f6-ce7e-41b4-9619-ec2c7e22d0b7.mp4

What do you mean? The jump button is bound to W.

**Comment by btzr-io** [comment]
> What do you mean? The jump button is bound to W.

I had vertical sync off, after enabling the issue is gone.

![image](https://user-images.githubusercontent.com/14793624/217967456-d8b23659-5c79-455c-b534-45334a2cf57f.png)

**Comment by RechieKho** [comment]
Weird, I don't know Windows, I use debian.
